server:
  port: 9000

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: User
          uri: lb://User
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user
                fallbackuri: forward:/user-fallback

        - id: Wallet
          uri: lb://Wallet
          predicates:
            - Path=/api/v1/wallets/**
          filters:
            - name: CircuitBreaker
              args:
                name: wallet
                fallbackuri: forward:/wallet-fallback

        - id: Transaction
          uri: lb://Transaction
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - name: CircuitBreaker
              args:
                name: transaction
                fallbackuri: forward:/transaction-fallback

        - id: Content
          uri: lb://Content
          predicates:
            - Path=/api/v1/contents/**
          filters:
            - name: CircuitBreaker
              args:
                name: content
                fallbackuri: forward:/content-fallback

        - id: Documentation
          uri: lb://Documentation
          predicates:
            - Path=/api/v1/documentation/**
          filters:
            - name: CircuitBreaker
              args:
                name: documentation
                fallbackuri: forward:/documentation-fallback

        - id: Order
          uri: lb://Order
          predicates:
            - Path=/api/v1/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order
                fallbackuri: forward:/order-fallback

        - id: Stock
          uri: lb://Stock
          predicates:
            - Path=/api/v1/stock/**
          filters:
            - name: CircuitBreaker
              args:
                name: stock
                fallbackuri: forward:/stock-fallback

        - id: Email
          uri: lb://Email
          predicates:
            - Path=/api/v1/email/**
          filters:
            - name: CircuitBreaker
              args:
                name: email
                fallbackuri: forward:/email-fallback

        - id: BaseDomain
          uri: lb://BaseDomain
          predicates:
            - Path=/api/v1/base-domain/**
          filters:
            - name: CircuitBreaker
              args:
                name: base-domain
                fallbackuri: forward:/base-domain-fallback


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
