server:
  port: 5005

spring:
  application:
    name: Email
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/email?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  zipkin:
    base-url: http://localhost:9411
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

api:
  basepath-order: /api/v1/emails
