server:
  port: 9003


spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabian-emmanuel/config-server.git
          clone-on-start: true
